### ISSUE TITLE
maintenance: add suitable License

### ISSUE THREAD

**Issue by abhiramtilakiiit** [PraneethJain/pentagon-megathon#12]
Proposed Changes:
- [ ] Perform a community poll to decide a suitable license.
- [ ] Add the license by making a `LICENSE` file in root

Options ( also mention version ):
   - GNU General Public License (GPL)
   - The Apache License.
   - Berkeley Software Distribution (BSD) - Zero clause, I-clause, II-clause, III-clause
   - Common Development and Distribution License (CDDL)
   - MIT License.

**Comment by abhiramtilakiiit** [comment]
https://take.quiz-maker.com/poll4986408xD7E1407B-153

**Comment by abhiramtilakiiit** [comment]
So here are the results: 
https://take.quiz-maker.com/results4986408xD7E1407B-153#tab-2

MIT: 40% ( 2 votes )
BSD: 40% ( 2 votes )
GPL: 20% (1 votes )

I am going with BSD ( third clause ) license because we will get credit since they can't change our org name in license.

**Comment by PraneethJain** [comment]
Alright, add it and create a PR
