### ISSUE TITLE
maintenance: Change presentation format

### ISSUE THREAD

**Issue by abhiramtilakiiit** [PraneethJain/pentagon-megathon#13]
Proposed Changes:
- [x] Make canva presentation view only

**Comment by harshvardhanrana** [comment]
The canva link has animations but .pptx doesn't display animations

**Comment by pingu-73** [comment]
@harshvardhanrana does this presentation has **Public view** attribute or **any-one can edit** attribute?

**Comment by harshvardhanrana** [comment]
Done.

**Comment by abhiramtilakiiit** [comment]
For this time it is ok, but
Next time, please find themes and templates elsewhere, which can be used or editted locally instead of 
using some website, we don't have control over how long the link is valid and stuff.
